# Generated by Django 3.2.5 on 2021-08-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('ordinary', 'Ordinary')], default='ordinary', max_length=10),
        ),
    ]
